# Generated by Django 2.0.5 on 2018-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='lock_status',
            field=models.CharField(max_length=10),
        ),
    ]
